CREATE TABLE `mails` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`src` VARCHAR(100) NOT NULL DEFAULT '0',
	`dst` VARCHAR(100) NOT NULL DEFAULT '0',
	`content` VARCHAR(500) NOT NULL DEFAULT '0',
	`time` VARCHAR(500) NOT NULL DEFAULT '0',
	`state` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

ALTER TABLE `users`
	ADD COLUMN `status` INT(11) NOT NULL DEFAULT '0' AFTER `role`;
